export const SET_CURRENTSONG= 'SET_CURRENTSONG'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_CURRENTSONG_INFO = 'SET_CURRENTSONG_INFO'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_CURRENTSONG_INDEX = 'SET_CURRENTSONG_INDEX'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST'

export const SET_TYPE = 'SET_TYPE'

export const SET_AREA = 'SET_AREA'

export const SET_PLAY_HISTORY = 'SET_PLAY_HOSTORY'

export const SET_SEARCH_RES = 'SET_SEARCH_RES'

export const SET_SEARCH_SONG = 'SET_SEARCH_SONG'

export const SET_USERINFO = 'SET_USERINFO'

export const SET_USER_PLAYLIST = "SET_USER_PLAYLIST"